language: node_js
dist: trusty
sudo: required
node_js: 14
script:
  - npm run test

cache:
  directories:
    - node_modules
env:
  global:
    - BX_APP=watson-assistant-simple
    - BX_API=https://api.ng.bluemix.net
    - BX_ORGANIZATION=WatsonPlatformServices
    - BX_SPACE=demos
before_deploy: npm install -g bx-blue-green
deploy:
  - provider: script
    skip_cleanup: true
    script: bx-blue-green-travis
    on:
      branch: master
      repo: watson-developer-cloud/assistant-simple
  - provider: script
    skip_cleanup: true
    script: npx -p node@14 -c "npx semantic-release"
